name: coverage

on:
  push:
    branches:
    - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/shared-setup
 
      # The runner image comes with a later version gradle that does not work with antq unit tests yet
      - name: Install Gradle for antq
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.14.3'

      - name: Run cloverage
        run: make coverage

      - name: Upload reports
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./target/coverage/codecov.json
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
