name: lint
on: [push, pull_request]

jobs:
  clj-kondo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeLaGuardo/setup-clojure@master
        with:
          bb: latest
      - run: bb lint-kondo

  cljstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeLaGuardo/setup-clojure@master
        with:
          bb: latest
      - run: bb lint-cljstyle check --report -v
