name: test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        java: ['11', '17', '21']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@master
        with:
          bb: latest
          cli: latest
          lein: latest
      # The runner image comes with a later version gradle that does not work with antq unit tests yet
      - name: Install Gradle for antq
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.14.3'
      - uses: actions/cache@v6
        with:
          path: ~/.m2
          key: test-m2-${{ hashFiles('deps.edn') }}-v1

      - name: run unit tests
        run: bb test-clj --clojure-version all --skip-meta integration

      - name: run integration tests
        run: bb test-clj --focus-meta integration
